config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  root to: "users#index"
  resources :users, only: %i[index]

  resources :groups, only: %i[index new create show destroy update] do
    resources :entities, only: %i[index new create destroy update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user, foreign_key: :author_id
  belongs_to :group

  validates :name, presence: true, length: { maximum: 100 }
  validates :amount, presence: true, numericality: { greater_than: 0, less_than: 100_000_000 }
  validates :user_id, presence: true

  validate :author_belongs_to_user

  private

  def author_belongs_to_user
    return if user_id == author_id

    errors.add(:author_id, 'must belong to the same user')
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entities, dependent: :delete_all

  validates :name, presence: true, length: { maximum: 100 }
  validates :icon, presence: true

  def recent_transactions
    entities.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 100 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 } # Adjust minimum length as needed

  has_many :groups, dependent: :destroy
  has_many :entities, foreign_key: :author_id, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  private

  def after_sign_in_path_for(_resource)
    groups_path # Redirect to groups index after sign-in
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show update destroy]

  # GET /items
  def index
    @group = Group.find(params[:group_id])
    @entities = Entity.where(group_id: @group.id).order(id: :desc)
    @total_amount = @entities.sum(:amount)
  end

  def new
    @group = Group.find(params[:group_id])
    @entity = Entity.new
  end

  # POST /items
  def create
    @group = Group.find(params[:group_id])
    @entity = @group.entities.build(entity_params) # Build a new entity associated with the group

    @entity.user_id = current_user.id # Set the user association
    @entity.author_id = current_user.id # Set the author association (if applicable)

    if @entity.save
      redirect_to group_entities_path(@group), notice: 'Transaction added successfully'
    else
      render :new, alert: 'Failed to add transaction'
    end
  end

  # DELETE /items/1
  def destroy
    @entity = Entity.find(params[:id])

    if @entity.destroy
      redirect_to group_entities_path, notice: 'Transaction removed successfully'
    else
      render :index, alert: 'Failed to remove Transaction'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @item = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show update destroy]

  # GET /groups
  def index
    @user = current_user
    @groups = @user.groups.includes(:entities).order(id: :desc)
  end

  def create
    add_group = current_user.groups.new(group_params)
    # @group = Group.new(group_params)

    if add_group.save
      # render json: @group, status: :created, location: @group
      redirect_to groups_path, notice: 'Category added successfully'
    else
      # render json: @group.errors, status: :unprocessable_entity
      render :new, status: :unprocessable_entity, alert: 'Failed to add category'
    end
  end

  # PATCH/PUT /groups/1
  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path, notice: 'Category updated successfully'
    else
      render :edit, alert: 'Failed to update category'
    end
  end

  # DELETE /groups/1
  def destroy
    @user = current_user
    @group = Group.find(params[:id])

    if @group.destroy
      redirect_to groups_path, notice: 'Category removed successfully'
    else
      render :index, alert: 'Failed to remove category'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  def determine_layout
    user_signed_in? ? 'application' : 'unauthenticated'
  end

  # Only allow a list of trusted parameters through.
  def group_params
    # params.require(:group).permit(:name, :icon)
    params.permit(:name, :icon)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  before_action :set_user, only: %i[show update destroy]

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/index.html.erb
<nav>
  <div>
    <%= link_to image_tag("https://img.icons8.com/ios-filled/48/ffffff/long-arrow-left.png"), groups_path, class: "btn"  %>
  </div>
  <h1 class="color-white">TRANSACTIONS</h1>
  <img src="https://img.icons8.com/sf-black/48/ffffff/search.png"/>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="banner">
  <div class="cat-image">
    <%= image_tag @group.icon rescue image_tag 'https://img.icons8.com/?size=512&id=kLORTzuNOM2d&format=png'%>
  </div>
  <h1><%= @group.name %></h1>
  <div>
    <p></p>
  </div>
  <div>
  </div>
</div>
<main>
   <div>
      <% if @entities.blank? %>
         <p>No Transaction Yet!</p>
      <% else %>
         <ul class="card-list">
            <% @entities.each do |payment| %>
               <li class="transaction-card hover">
                  <a><h2><%= payment.name %></h2></a>
                  <a>$<%= payment.amount %></a>
                  <%= button_to "Delete", group_entity_path(user_id: payment.user.id, group_id: payment.group.id, id: payment.id), method: :delete, class: "del-btn"  %>
               </li>
            <% end %>
         </ul>
      <% end %>
      <div class="total-banner">
         <h4>Total Amount</h4>
         <p>$<%=@total_amount %></p>
      </div>
   </div>
   <button class="green-btn" type="button">
    <%= link_to "ADD A NEW TRANSACTION", new_group_entity_path %>
  </button>
</main>

app/views/entities/new.html.erb
<nav>
  <div>
    <%= link_to image_tag("https://img.icons8.com/ios-filled/48/ffffff/long-arrow-left.png"), group_entities_path, class: "btn"  %>
  </div>
  <h1 class="color-white">NEW TRANSACTIONS</h1>
  <img src="https://img.icons8.com/sf-black/48/ffffff/search.png"/>
</nav>
<div class="center">
  <h1>ADD A NEW TRANSACTION</h1>
  <%= form_with model: @entity, url: group_entities_path(@group), data: { turbo: false } do |f| %>
      <br/>
      <br/>
      <%= f.text_field :name, placeholder: 'Name', class: "form-field"%>
      <br/>
      <br/>
      <%= f.number_field :amount, placeholder: 'Amount', class: "form-field"%>
      <br/>
      <br/>
      <%= f.submit 'Add Transaction', class:'green-btn'%>
  <% end %>
</div>

app/views/groups/index.html.erb
<main class="splash_screen">
  <div class="app_name">
      <nav>
        <%= link_to image_tag("https://img.icons8.com/sf-regular/48/ffffff/exit.png"), destroy_user_session_path, method: :delete %>
         <h1 class="categories">CATEGORIES</h1>
        <img src="https://img.icons8.com/sf-black/48/ffffff/search.png"/>
      </nav>
      <main>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <div class="card-list">
          <% @groups.each do |category| %>
            <div class="card hover">
              <div class="flex-row">
                <div class="cat-image">
                  <%= image_tag category.icon rescue image_tag('https://img.icons8.com/?size=512&id=kLORTzuNOM2d&format=png', alt: "Category Icon") %>
                </div>
                <div>
                  <h2><%= link_to category.name, group_entities_path(group_id: category.id, class: 'text') %></h2>
                  <br/>
                  <hr />
                  <br/>
                  <p><%= l category.created_at.to_date, format: :long %></p>
                </div>
              </div>
              <div class="cat-total">
                <p>$<%= Entity.where(group_id: category.id).sum(:amount) %></p>
                <br/>
                <%= button_to 'Delete', group_path(id: category.id), method: :delete, class: 'del-btn' %>
              </div>
            </div>
          <% end %>
        </div>
        <button class="green-btn" type="button" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Add a new category">
          <%= link_to 'Add a new category', new_group_path %>
        </button>
      </main>
    </div>
  </main>
</main>

app/views/groups/new.html.erb
<nav>
  <div>
    <%= link_to image_tag("https://img.icons8.com/ios-filled/48/ffffff/long-arrow-left.png"), groups_path, class: "btn"  %>
  </div>
  <h1 class="color-white">NEW CATEGORY</h1>
  <img src="https://img.icons8.com/sf-black/48/ffffff/search.png"/>
</nav>
<div class="center">
<h1>ADD A NEW CATEGORY</h1>
  <div class="card-list">
    <%= form_with model: @group, url: groups_path do |f| %>   
      <br/>
      <%= f.text_field :icon, placeholder: "Enter the Icon link. e.g: https://icon.com", class: "form-field" %>
      <br/>
      <br/>
      <%= f.text_field :name, placeholder: "Name", class: "form-field"%>
      <br/>
      <br/>
      <%= f.submit 'Save', class: 'green-btn'%>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<main class="splash-screen">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>  
<div class="app-name">
    <h1>Budget App</h1>
  </div>  
      <div class="buttons-container">
        <button class="blue-btn">
          <%= link_to('LOG IN', "/users/sign_in") %>
        </button>
        <button class="white-btn">
          <%= link_to('SIGN UP', "/users/sign_up") %>
        </button>
        </div>
</main>